import { Injectable, OnApplicationBootstrap, Logger, NotFoundException } from '@nestjs/common';
import type {
  AcceptConsentDto,
  ConsentStatus,
  LegalDocumentType,
  LegalDocument,
} from '@repo/types';
import { ILegalRepository } from '../domain/repositories/legal.repository';
import type {
  ILegalDocument,
  ILegalDocumentDocument,
  IConsentRecordDocument,
} from '@repo/db';
import { IConsentRepository } from '../domain/repositories/consent.repository';

@Injectable()
export class LegalService implements OnApplicationBootstrap {
  private readonly logger = new Logger(LegalService.name);
  private readonly VERSIONS: Record<LegalDocumentType, string> = {
    privacy: '1.0',
    cookie: '1.0',
    terms: '1.0',
  };

  constructor(
    private readonly legalRepository: ILegalRepository,
    private readonly consentRepository: IConsentRepository,
  ) {}

  async onApplicationBootstrap(): Promise<void> {
    await this.seedPolicies();
  }

  private async seedPolicies(): Promise<void> {
    const policies: Partial<ILegalDocument>[] = [
      {
        type: 'privacy',
        version: this.VERSIONS.privacy,
        title: 'Privacy Policy',
        content: `
# Privacy Policy for Recall

Effective Date: March 26, 2026

## 1. Information We Collect
Recall collects personal knowledge information, including:
- Uploaded documents (PDFs, images, text)
- Extracted transcripts from audio/video
- Vector embeddings of your data (stored in Qdrant)
- Chat interactions with our AI assistant

## 2. How We Use Your Data
Your data is used solely to provide personal knowledge management services. We use:
- OpenRouter and third-party LLM providers to process your queries.
- Persistent storage in MongoDB and Redis for session management.
- Qdrant for semantic search and retrieval.

## 3. Data Sharing and Processing
We do NOT sell your data. Data is shared with AI providers (via OpenRouter) strictly for processing your requests. These providers are bound by their own privacy policies.

## 4. Your Rights
You have the right to:
- Access your data
- Request deletion of your account and all associated data
- Export your knowledge graph

## 5. Contact
For privacy-related inquiries, contact privacy@recall.ai
        `,
        effectiveDate: new Date(),
        active: true,
      },
      {
        type: 'cookie',
        version: this.VERSIONS.cookie,
        title: 'Cookie Policy',
        content: `
# Cookie Policy for Recall

Effective Date: March 26, 2026

## 1. What are Cookies?
Cookies are small text files stored on your device to enhance your experience.

## 2. How We Use Cookies
- **Essential Cookies**: Necessary for authentication and session management.
- **Functional Cookies**: Used to remember your preferences (e.g., theme, LLM settings).
- **Analytics Cookies**: Help us understand how you use Recall to improve the service.

## 3. Managing Cookies
You can manage or disable cookies through your browser settings, though some features of Recall may not function correctly without them.
        `,
        effectiveDate: new Date(),
        active: true,
      },
      {
        type: 'terms',
        version: this.VERSIONS.terms,
        title: 'Terms of Service',
        content: `
# Terms of Service for Recall

Effective Date: March 26, 2026

## 1. Acceptance of Terms
By accessing or using Recall, you agree to be bound by these Terms of Service.

## 2. Description of Service
Recall is an AI-powered personal knowledge engine that allows users to upload, organize, and query their personal data.

## 3. User Responsibilities
You are responsible for the content you upload and must ensure you have the necessary rights to use and process such data.

## 4. Limitations of Liability
Recall is provided "as is". We are not liable for any data loss or inaccuracies generated by the AI components.

## 5. Termination
We reserve the right to terminate or suspend access to our service for any reason, including violation of these terms.
        `,
        effectiveDate: new Date(),
        active: true,
      },
    ];

    const policyTypes: LegalDocumentType[] = ['privacy', 'cookie', 'terms'];

    for (const type of policyTypes) {
      const version = this.VERSIONS[type];
      const policyData = policies.find((p) => p.type === type);
      if (!policyData) continue;

      const existing = await this.legalRepository.findByVersion(type, version);

      if (!existing) {
        await this.legalRepository.create({
          ...policyData,
          type,
          version,
        });
        this.logger.log(`Seeded ${type} policy version ${version}`);
      } else if (!existing.active) {
        existing.active = true;
        await existing.save();
      }
    }
  }

  async getActivePolicy(type: LegalDocumentType): Promise<LegalDocument> {
    const policy = await this.legalRepository.findActivePolicy(type);
    if (!policy) {
      throw new NotFoundException(`${type} policy not found`);
    }
    return this.mapToDto(policy);
  }

  private mapToDto(doc: ILegalDocumentDocument): LegalDocument {
    return {
      id: doc.id,
      type: doc.type,
      version: doc.version,
      title: doc.title,
      content: doc.content,
      effectiveDate: doc.effectiveDate,
      active: doc.active,
      createdAt: doc.createdAt,
      updatedAt: doc.updatedAt,
    };
  }

  async getConsentStatus(
    userId?: string,
    anonymousId?: string,
  ): Promise<ConsentStatus> {
    let latestConsent: IConsentRecordDocument | null = null;

    if (userId) {
      latestConsent = await this.consentRepository.findLatestByUserId(userId);
    } else if (anonymousId) {
      latestConsent =
        await this.consentRepository.findLatestByAnonymousId(anonymousId);
    }

    const checkAccepted = (type: LegalDocumentType): boolean => {
      const versions = latestConsent?.policyVersions;
      return !!versions && versions[type] === this.VERSIONS[type];
    };

    return {
      privacyAccepted: checkAccepted('privacy'),
      cookieAccepted: checkAccepted('cookie'),
      termsAccepted: checkAccepted('terms'),
      acceptedCategories: latestConsent?.categories || [],
      requiredVersions: this.VERSIONS,
    };
  }

  async acceptConsent(
    userId: string | undefined,
    anonymousId: string | undefined,
    dto: AcceptConsentDto,
    ip: string,
    userAgent: string,
  ): Promise<ConsentStatus> {
    await this.consentRepository.create({
      userId,
      anonymousId,
      policyVersions: dto.policyVersions,
      categories: dto.categories,
      ip,
      userAgent,
      timestamp: new Date(),
    });

    return this.getConsentStatus(userId, anonymousId);
  }

  getCurrentVersions(): Record<LegalDocumentType, string> {
    return this.VERSIONS;
  }
}
